---
version: "2.1.0"
configurations: 
  debug: ~
  release: ~
targets: 
  SocialSmileyStore: 
    configuration: 
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      FRAMEWORK_SEARCH_PATHS: 
        - $(inherited)
        - Carthage/Build/iOS
      INFOPLIST_FILE: src/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.socialsuperstore.socialsmileystore
    i18n-resources: lproj
    platform: ios
    references: 
      - 
        codeSignOnCopy: true
        copy: true
        location: Carthage/Build/iOS/Smile.framework
    sources: src
    type: ":application"
variants: 
  $base: 
    abstract: true
  SocialSmileyStore: ~
